import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { UserProvider } from "./_components/Contexts/UserContext";
import { ErrorProvider } from "./_components/Contexts/ErrorContext";
import { SuccessProvider } from "./_components/Contexts/SuccessContext";
import ErrorMessage from "./_components/Contexts/ErrorMessage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ErrorProvider>
          <SuccessProvider>
            <UserProvider>
              <Navbar />
              <ErrorMessage />
              {children}
            </UserProvider>
          </SuccessProvider>
        </ErrorProvider>
      </body>
    </html>
  );
}
